apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data
  namespace: storage-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
