CREATE USER n8n_user WITH PASSWORD '9Hv83eraPIDJKz1UIdo=';

CREATE DATABASE n8n OWNER n8n_user;

GRANT CONNECT ON DATABASE n8n TO admin;

\c n8n

GRANT USAGE ON SCHEMA public TO admin;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO admin;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO admin;