apiVersion: ENC[AES256_GCM,data:7mU=,iv:zFMx8qn1SYUVASGJI3e1/4i1wc9khJut/xzrY+derYU=,tag:DEl1VSDo2fyZwdkID3pnMA==,type:str]
kind: ENC[AES256_GCM,data:i1hW3f9W,iv:xv26GVRkUNeqnk5dVeuxH/vX7WfHYjIy+ByRRP6+BD0=,tag:RJVORlmKTWRIVLrB6vPC4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jqLt8ki2uhXP58bQ6LEM,iv:5WT2StMIVT6JJ6EodeLfQsT8mzFvD4JVI6axzO0GvE8=,tag:Isz1S9axVOLCUWz4Ckuhug==,type:str]
    namespace: ENC[AES256_GCM,data:Cy1kXfzuK2Y=,iv:YB91QMOSYHFuClEphGvgsQeCZVxH6BfKN2SOs8Rt02U=,tag:yiwNocGirzWjPVbLH9FJfg==,type:str]
type: ENC[AES256_GCM,data:VjCOrfHN,iv:ZvvQw52gEgh9DYnP2Vh+76fwPdj66u1KKYbEB39hbr8=,tag:xZ9vFo+EQqbgrEwfzBdfdw==,type:str]
stringData:
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:D8gDl6EA52d80UeMN8cim0hjP0ziMGPF8zdnX5QsKynluG8+EgBGsuk6j0Y=,iv:xj0XwjUwzo81L+1JoLFIHR28Oq3nUAs5ytSymhKe8uI=,tag:jxUQ1+IKBTo9QmuaWNLAJQ==,type:str]
sops:
    age:
        - recipient: age1rtc6c98luvq36xrszf79fkypc8faa94kye99ana27nxyc7vvwams4drggc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob1A3eXFTenUvcWxYS1B0
            cVhJR01OVnJwZnpLNUExaWhVRE1KbVhIOEFzCklJczZhQ3o5eW9rM2VPM2IreGE5
            MTgwQkxwT3BQbGc2WjFXYTJUcnZsazQKLS0tIGxTQksrcHhnbnlKYXYwY1NCS2Vp
            VGFBM0xTYmpJa2t2dVJTQ0tGaW5NRzgKJSQr8GXdJeQddJkeV1+4e/wxmwGQUu+g
            OyO+JhukWRaVOo3+uHIvnwteDHqoO1b4dHx/EPOFwdydjEhTZCykvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T00:01:05Z"
    mac: ENC[AES256_GCM,data:YtaCFhVmyeT7YiuD67nz5+PzEm7NIhR+HJ1Fzp0gJDznhrBEpO1FZY+tcRgHYVKYJ9f07mEULovPahWXzA8gDiWHLZdW02j14X4Qvi+uzCa3YJlOlVKrX6CMvQKezBvRVPbY7Et85aTWmXmU26lt3gyUy9nqNTjoTkD2ao5RDs4=,iv:zXqU1n9IU5hHciGVFZjPukBvEQqcpjAhDZ4qk+L/Zyc=,tag:TPwLYmw+kBxSNdFWWtwQ8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
