apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: "http://ntfy.k8s.homelab.local"
    cache-file: /var/cache/ntfy/cache.db
    cache-duration: 12h
    auth-file: /var/lib/ntfy/user.db
    auth-default-access: deny-all
    behind-proxy: true
