apiVersion: ENC[AES256_GCM,data:8qI=,iv:KtkhyQCWLrCa29LgyUdsJ/J35AzyVKwqp5clQKE6VyI=,tag:b2jEbjKeLdnHmhLnVYkfXA==,type:str]
kind: ENC[AES256_GCM,data:5cJPrC6l,iv:6bbQ7cD7/k42F+/JIIvunfG8PKk/6mvweO9odLGHk90=,tag:LIQN1gX2do7Fizx9BUv1NQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jjnInDjpzLaDOXudtrmt,iv:/qrWoDX8ptskHaQ7AelEDA6dTZYFYXEHPgwLEXDddE0=,tag:o5axW75EC9a2NOk2TpLu8A==,type:str]
    namespace: ENC[AES256_GCM,data:zoqONBqIHJgtCg==,iv:UZ6IOx6c3WLIE5TC8/ECcEl3w5hGxcNjuOJN7WxUFSI=,tag:z7tBdLXUFBoCXhWpAfv9Jg==,type:str]
type: ENC[AES256_GCM,data:jH0QAqq3,iv:As5a0AkAJjDe1SilJ9SRJCxqIuVUaUz2bBj817NvlB0=,tag:YHCESgHb8XGwshty3kD+3g==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:E28Wsic=,iv:0//edJQBKfRbrs2kZbsvPjj4E1kunGr4+v0i5cdK7AM=,tag:vnMCJDkBsX6LlncJaNaouA==,type:str]
    admin-password: ENC[AES256_GCM,data:O/GsqTJN+80hjtCuExd/7IjJ6w==,iv:p8stu46QYhq9ytRmNiuAXQSxqJG+Hoo8GPADZgDuNZU=,tag:6aDLEL/1FvjqesWnff9tjA==,type:str]
sops:
    age:
        - recipient: age1rtc6c98luvq36xrszf79fkypc8faa94kye99ana27nxyc7vvwams4drggc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRU9xb3gzcEREMWRob0Za
            LzFXU0U1M3JaQ1B4VHVMS28rWjVvUy9TMmo4ClF5eVhvcE9oM3drWEJ4RjJlSk94
            VHd3YWxDYWZOa29BTFJud21aUEtHcm8KLS0tIDNTWjltNGM1UWZaMjB3MnJvcnJX
            Ulg4UURaM2UrZ25pKzlQSTN1QnY2bncKzKxtlDzS9BBvfKQ1i28PPItzTDjnYaxa
            C5pqifFfZRrbh8fYyd0LWDBL4yxNjAF/YGGSKSTbnpHH54iPTDDnmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T22:46:25Z"
    mac: ENC[AES256_GCM,data:wDVIEwxLC+/oojnUzJ5yTV+e8hGE+WlliA6tCanfll/71/6PHqXP7AfdEdLJ6PMJoqAS070XGt+7HJWkHkwGoe1QlS8rKseos4W8HDiE5zuynHLcvIdEXFdYINxqidmyrcH2EH9Y6xZObG2HQIEX023yiT4B/7Zg2WRTRvu7tjQ=,iv:7U/uACIiODHVxuczTFoBiJlgiWOmYP2fXZSxBARaQEc=,tag:UAqGrMR2HT9e7cGn0O5jyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
