apiVersion: ENC[AES256_GCM,data:Apc=,iv:qBrAF57CTw85NN/GOJLDdwTP3NpbdwJ91Ri/UM6crCI=,tag:azpU7M1WhdpM1yTrBEkJ/A==,type:str]
kind: ENC[AES256_GCM,data:SCS5ZpQ0,iv:PxBk459TSjTrFCCNCDYnOXHrI6eCRgSdQ1c/YjPPSX0=,tag:m2YMoT26hR9GehFCbxjvCA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FMzWp1FhoNBohMQ=,iv:Q9sCNlFBGoNdKhvog0k73FZO5tusyDM1BDzdlJqSozU=,tag:8kE5nQdRR4g3HwiMqBxVMg==,type:str]
    namespace: ENC[AES256_GCM,data:FRy8j3EGWT8jpw==,iv:V0+gzYRreuc6xDZQTuMdTPomxTms9NqSDIcQedWtB30=,tag:c5btD6O0R5G4Rn3b9/3Yzg==,type:str]
type: ENC[AES256_GCM,data:gC/EWa0Y,iv:z17HQMWh4OoAumqoUQdBWaQSeIYKoG4UKfEdq8CHsuY=,tag:646UT3jMTXMD549DvAjsUQ==,type:str]
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:PcfWFeT9YOPStHn8ZfM56IXRNoo=,iv:zj+JUMQc+l79lhCk1rrowYYRTud/Sa4tygs/0Mjxyh4=,tag:bkERPP7yLML/NxL22xQDyQ==,type:str]
sops:
    age:
        - recipient: age1rtc6c98luvq36xrszf79fkypc8faa94kye99ana27nxyc7vvwams4drggc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK1UxRkVTNEFEanhKbEIw
            MEhSZVJyMWRVQWRFTGVYclJLbG9pS1hFWW1VCnVEbVdJNWVqdTBOaEZiTWpEL253
            cUNMU1Q0VEdoaDIweGlwOWZZOWZuMmsKLS0tIEdyNTQ4dFhqQW5sTE45T0FUMjcv
            QlhZL255Rm1VRFdqYkF5c3FOeWR1eWsK4w/a76yEHTQKe6y8EVSvirB/BIvgY+tx
            CL9/6xAcfenwVbF45ED7UFPviyVcTnS+60zBhCILrkRD6oHDucpDQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T10:30:30Z"
    mac: ENC[AES256_GCM,data:0w5VxusRsEelcxzD4yOzOlXHTyv9BI13BXez14qr3krYqqEi/fRAeQojfLl7i0DmJhtYS1kf73Sln8ET++AKov42fyDeWtPZ2IYcQ0jZ1O1tDhwg6NGrQUTAa69sV4WzaVKf+qXPI3ADm+CioPWWWRwAV3srIRSR5sONXQqDP2I=,iv:U0aaAe3ZbzksA+F/DqI8KqqQJDgweoIDiqenf+eTJ5w=,tag:s6m1aux8Ve/xI8wza9ikXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
