name: Build and deploy

on:
  push:
    branches: [main]
    paths:
      - "apps/test-app/**"

jobs:
  detect-changes:
    runs-on: [self-hosted,homelab]
    outputs:
      apps: ${{ steps.changes.outputs.apps }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            test-app:
              - 'apps/test-app/**'

  build-test-app:
    needs: detect-changes
    # if: ${{needs.detect-changes.outputs.apps.test-app == 'true'}}
    runs-on: [self-hosted, homelab]
    steps:
      - uses: actions/checkout@v4
      - name: build and push
        run: |
          docker build -t registr.k8s.homelab.local/test-app:${{github.sha }} /apps/test-app/
          docker push register.k8s.homelab.local/test-app:${{ github.sha }}
