name: Build and deploy

on:
  push:
    branches: [main]
    paths:
      - "apps/test-app/**"

jobs:
  build-test-app:
    runs-on: [self-hosted, homelab]
    steps:
      - uses: actions/checkout@v4
      - name: build and push
        run: |
          docker build -t registry.k8s.homelab.local/test-app:${{ github.sha }} /apps/test-app/
          docker push registry.k8s.homelab.local/test-app:${{ github.sha }}
